main: com.github.samthepsychoticleprechaun.KeyStoneCore.KeyStoneCore
name: Key Stone Plugin
version: 0.1
description: A broad suite of server plug-ins designed for that all-in-one package that server managers deserve!
commands:
    